name: Update Streak

on:
  schedule:
    - cron: '30 22 * * *'  # Runs at 10:30 PM UTC every day
  workflow_dispatch:  # Allows manual triggering

jobs:
  update-streak:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Add Today's Date and Update Streak
        run: |
          # Set the timezone to India Standard Time (IST)
          export TZ="Asia/Kolkata"
          
          # Get today's date in IST
          today=$(date +"%Y-%m-%d")
          
          # Check if today's date is already in the table
          if ! grep -q "| $today |" README.md; then
            # Append today's date with empty values if missing
            sed -i "/| Date       |/a| $today | 0 | 0 |" README.md
          fi

          # Calculate streaks for 's' and 'b'
          s_streak=$(awk '/\|/{if($3=="1"){s++}else{s=0}}END{print s}' README.md)
          b_streak=$(awk '/\|/{if($4=="1"){b++}else{b=0}}END{print b}' README.md)

          # Remove old streak entries before inserting new ones
          sed -i '/\*\*s:\*\* [0-9]* days/d' README.md
          sed -i '/\*\*b:\*\* [0-9]* days/d' README.md

          # Insert updated streak values
          sed -i "2i- **s:** $s_streak days" README.md
          sed -i "3i- **b:** $b_streak days" README.md

      - name: Format Markdown with Prettier
        run: |
          npm install -g prettier
          prettier --write README.md

      - name: Commit and Push Changes
        run: |
          git config --global user.name "github-actions[bot]"
          git config --global user.email "github-actions[bot]@users.noreply.github.com"
          git add README.md
          git commit -m "Update streak for $today" || echo "No changes to commit"
          git push
